version: '3'

name: inception

volumes:
  data:

services:
  mariadb:
    volumes:  #수정필요
      - ~/Develop/Docker/data/mysql:/var/lib/mysql/
    image: mariadb:0.0
    build: ./requirements/mariadb/
    restart: always
    expose:
      - "3306"
    networks:
      - inner
    tty: true
    env_file:
      - ".env"
  wordpress:
    # image: wordpress:0.0
    # build: ./requirements/wordpress
    image: debian:bookworm
    restart: always
    volumes:
      - data:/var/www/html
    expose:
      - "9000"
    networks:
      - inner
    tty : true
    depends_on:
      - nginx
  nginx:
    image: debian:bookworm
    restart: always
    ports:
      - "443:443"
    volumes:
      - data:/var/www/html
    networks:
      - inner
    tty: true
    depends_on:
      - mariadb

networks:
  inner:
    driver: bridge